[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "langchain-community==0.3.10",
    "langchain==0.3.10",
    "langchain-core==0.3.22",
    "langchain-openai==0.2.11",
    "langchainhub==0.1.21",
    "langchain-pinecone==0.2.0",
    "streamlit==1.40.2",
    "python-dotenv>=1.0.1",
]
